apiVersion: v1
kind: Service
metadata:
  name: soc-dashboard
  namespace: security-tools
  labels:
    app.kubernetes.io/name: soc-dashboard
spec:
  selector:
    app.kubernetes.io/name: soc-dashboard
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
