// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: ingest.proto

package ingestpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlertIngestService_IngestAlert_FullMethodName = "/soc.ingest.v1.AlertIngestService/IngestAlert"
)

// AlertIngestServiceClient is the client API for AlertIngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AlertIngestService is the high-throughput write path for pushing security
// alerts into the SOC Dashboard. Both REST (port 8001) and gRPC (port 9001)
// transports are served by the same underlying service implementation.
type AlertIngestServiceClient interface {
	IngestAlert(ctx context.Context, in *IngestAlertRequest, opts ...grpc.CallOption) (*IngestAlertResponse, error)
}

type alertIngestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertIngestServiceClient(cc grpc.ClientConnInterface) AlertIngestServiceClient {
	return &alertIngestServiceClient{cc}
}

func (c *alertIngestServiceClient) IngestAlert(ctx context.Context, in *IngestAlertRequest, opts ...grpc.CallOption) (*IngestAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestAlertResponse)
	err := c.cc.Invoke(ctx, AlertIngestService_IngestAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertIngestServiceServer is the server API for AlertIngestService service.
// All implementations must embed UnimplementedAlertIngestServiceServer
// for forward compatibility.
//
// AlertIngestService is the high-throughput write path for pushing security
// alerts into the SOC Dashboard. Both REST (port 8001) and gRPC (port 9001)
// transports are served by the same underlying service implementation.
type AlertIngestServiceServer interface {
	IngestAlert(context.Context, *IngestAlertRequest) (*IngestAlertResponse, error)
	mustEmbedUnimplementedAlertIngestServiceServer()
}

// UnimplementedAlertIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlertIngestServiceServer struct{}

func (UnimplementedAlertIngestServiceServer) IngestAlert(context.Context, *IngestAlertRequest) (*IngestAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestAlert not implemented")
}
func (UnimplementedAlertIngestServiceServer) mustEmbedUnimplementedAlertIngestServiceServer() {}
func (UnimplementedAlertIngestServiceServer) testEmbeddedByValue()                            {}

// UnsafeAlertIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertIngestServiceServer will
// result in compilation errors.
type UnsafeAlertIngestServiceServer interface {
	mustEmbedUnimplementedAlertIngestServiceServer()
}

func RegisterAlertIngestServiceServer(s grpc.ServiceRegistrar, srv AlertIngestServiceServer) {
	// If the following call panics, it indicates UnimplementedAlertIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlertIngestService_ServiceDesc, srv)
}

func _AlertIngestService_IngestAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertIngestServiceServer).IngestAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertIngestService_IngestAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertIngestServiceServer).IngestAlert(ctx, req.(*IngestAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlertIngestService_ServiceDesc is the grpc.ServiceDesc for AlertIngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlertIngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "soc.ingest.v1.AlertIngestService",
	HandlerType: (*AlertIngestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestAlert",
			Handler:    _AlertIngestService_IngestAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ingest.proto",
}
