// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: ingest.proto

package ingestpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                                        // required
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`                                  // required: brute_force | port_scan | phishing | malware | anomaly
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`                                  // required: CRITICAL | HIGH | MEDIUM | LOW
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`                                      // optional: detecting sensor or tool name
	SourceIp      string                 `protobuf:"bytes,5,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`                  // optional: attacker IP (encrypted at rest)
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`                            // optional: human-readable detail (encrypted at rest)
	WorkflowRunId string                 `protobuf:"bytes,7,opt,name=workflow_run_id,json=workflowRunId,proto3" json:"workflow_run_id,omitempty"` // optional: Orkes Conductor run provenance
	RunMetadata   string                 `protobuf:"bytes,8,opt,name=run_metadata,json=runMetadata,proto3" json:"run_metadata,omitempty"`         // optional: JSON task-timing blob from Conductor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestAlertRequest) Reset() {
	*x = IngestAlertRequest{}
	mi := &file_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAlertRequest) ProtoMessage() {}

func (x *IngestAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAlertRequest.ProtoReflect.Descriptor instead.
func (*IngestAlertRequest) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *IngestAlertRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IngestAlertRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *IngestAlertRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *IngestAlertRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IngestAlertRequest) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *IngestAlertRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IngestAlertRequest) GetWorkflowRunId() string {
	if x != nil {
		return x.WorkflowRunId
	}
	return ""
}

func (x *IngestAlertRequest) GetRunMetadata() string {
	if x != nil {
		return x.RunMetadata
	}
	return ""
}

type IngestAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC 3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestAlertResponse) Reset() {
	*x = IngestAlertResponse{}
	mi := &file_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAlertResponse) ProtoMessage() {}

func (x *IngestAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAlertResponse.ProtoReflect.Descriptor instead.
func (*IngestAlertResponse) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *IngestAlertResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IngestAlertResponse) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *IngestAlertResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IngestAlertResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_ingest_proto protoreflect.FileDescriptor

const file_ingest_proto_rawDesc = "" +
	"\n" +
	"\fingest.proto\x12\rsoc.ingest.v1\"\x84\x02\n" +
	"\x12IngestAlertRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1b\n" +
	"\tsource_ip\x18\x05 \x01(\tR\bsourceIp\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12&\n" +
	"\x0fworkflow_run_id\x18\a \x01(\tR\rworkflowRunId\x12!\n" +
	"\frun_metadata\x18\b \x01(\tR\vrunMetadata\"x\n" +
	"\x13IngestAlertResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt2j\n" +
	"\x12AlertIngestService\x12T\n" +
	"\vIngestAlert\x12!.soc.ingest.v1.IngestAlertRequest\x1a\".soc.ingest.v1.IngestAlertResponseB6Z4github.com/Romil2112/SOC-Dashboard/internal/ingestpbb\x06proto3"

var (
	file_ingest_proto_rawDescOnce sync.Once
	file_ingest_proto_rawDescData []byte
)

func file_ingest_proto_rawDescGZIP() []byte {
	file_ingest_proto_rawDescOnce.Do(func() {
		file_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingest_proto_rawDesc), len(file_ingest_proto_rawDesc)))
	})
	return file_ingest_proto_rawDescData
}

var file_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ingest_proto_goTypes = []any{
	(*IngestAlertRequest)(nil),  // 0: soc.ingest.v1.IngestAlertRequest
	(*IngestAlertResponse)(nil), // 1: soc.ingest.v1.IngestAlertResponse
}
var file_ingest_proto_depIdxs = []int32{
	0, // 0: soc.ingest.v1.AlertIngestService.IngestAlert:input_type -> soc.ingest.v1.IngestAlertRequest
	1, // 1: soc.ingest.v1.AlertIngestService.IngestAlert:output_type -> soc.ingest.v1.IngestAlertResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ingest_proto_init() }
func file_ingest_proto_init() {
	if File_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingest_proto_rawDesc), len(file_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingest_proto_goTypes,
		DependencyIndexes: file_ingest_proto_depIdxs,
		MessageInfos:      file_ingest_proto_msgTypes,
	}.Build()
	File_ingest_proto = out.File
	file_ingest_proto_goTypes = nil
	file_ingest_proto_depIdxs = nil
}
